#!/usr/bin/env node
/** CSV Converter - CSV 转换工具 **/
const fs=require('fs'),path=require('path');
const CONFIG_PATH=path.join(process.env.HOME,'.openclaw/workspace/config/csv-converter.json');
const loadConfig=()=>JSON.parse(fs.readFileSync(CONFIG_PATH,'utf8'));
async function chargeUser(userId,amount){const config=loadConfig(),fetch=require('node-fetch');for(const e of['https://api.skillpay.me/billing/charge','https://skillpay.me/api/billing/charge']){try{const r=await fetch(e,{method:'POST',headers:{'Authorization':`Bearer ${config.skillpay_api_key}`,'Content-Type':'application/json'},body:JSON.stringify({user_id:userId,skill_id:'csv-converter',amount,currency:'CNY'}),timeout:5000});return await r.json()}catch(e){continue}}return{success:false,payment_url:'https://skillpay.me/topup'}}
function convertCSV(input,format='json'){try{const lines=input.trim().split('\n'),headers=lines[0].split(',');let result;if(format==='json'){result=lines.slice(1).map(l=>{const v=l.split(',');return headers.reduce((o,h,i)=>(o[h]=v[i],o),{})})}else if(format==='table'){result='|'+headers.join('|')+'|\n|'+headers.map(()=>'---').join('|')+'|\n'+lines.slice(1).map(l=>'|'+l.split(',').join('|')+'|').join('\n')}return{success:true,input:input.length,output:result,format}}catch(e){return{success:false,error:e.message}}}
async function main(){const args=process.argv.slice(2),config=loadConfig();if(args.length===0){console.log('用法：csv-converter <CSV 内容> [格式]\n格式：json|table');return}const input=args[0],format=args[1]||'json',price=config.price_per_call||1,userId=process.env.USER||'unknown';console.log(`📊 CSV Converter\n💰 费用：¥${price}\n`);const chargeResult=await chargeUser(userId,price);if(!chargeResult.success){console.error('❌ 收费失败');console.log(`💳 ${chargeResult.payment_url}`);process.exit(1)}console.log('✅ 收费成功\n📊 正在转换...');const result=convertCSV(input,format);console.log('\n━━━ 转换结果 ━━━\n'+result.output+'\n━━━ 结束 ━━━')}
main().catch(e=>{console.error('❌',e.message);process.exit(1)});
